version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: brewhouse-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=brewhouse

  app:
    build: .
    container_name: brewhouse-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/brewhouse
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
